"""contador_reservas

Revision ID: 096ce50927c7
Revises: a2fab18af748
Create Date: 2025-09-18 12:08:53.249175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '096ce50927c7'
down_revision = 'a2fab18af748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contador_reservas', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('contador_reservas')

    # ### end Alembic commands ###
