"""tipo-reserva

Revision ID: 3fac2a741f4a
Revises: c7c2f3a7c482
Create Date: 2025-09-18 11:17:54.482995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fac2a741f4a'
down_revision = 'c7c2f3a7c482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_reserva', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.drop_column('tipo_reserva')

    # ### end Alembic commands ###
