"""15Sep

Revision ID: 5ff16aa93293
Revises: 474a8b377612
Create Date: 2025-09-15 11:40:33.599640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ff16aa93293'
down_revision = '474a8b377612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio', sa.Float(), nullable=False))

    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monto', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.drop_column('monto')

    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_column('precio')

    # ### end Alembic commands ###
