"""17Sep

Revision ID: 776f4c00e0ef
Revises: 70dc3dbc9f56
Create Date: 2025-09-17 10:28:05.566228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '776f4c00e0ef'
down_revision = '70dc3dbc9f56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('session_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_token', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
