"""contador_reservas

Revision ID: 8d0052dfcf99
Revises: 096ce50927c7
Create Date: 2025-09-18 12:28:57.671164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d0052dfcf99'
down_revision = '096ce50927c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('contador_reservas',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('contador_reservas',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
