"""add ultimo_premio to User

Revision ID: a2fab18af748
Revises: 3fac2a741f4a
Create Date: 2025-09-18 11:34:15.081146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2fab18af748'
down_revision = '3fac2a741f4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultimo_premio', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('ultimo_premio')

    # ### end Alembic commands ###
